import Header from '@/components/Header/Header'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Searchbox from '@/components/Searchbox/Searchbox'

export const metadata = {
  title: 'IMDC',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Header/>
        <Navbar/>
        <Searchbox/>
        
        
        {children}</body>
    </html>
  )
}
